apiVersion: v1
kind: Service
metadata:
  name: blog-api
  namespace: blog-service
  labels:
    app: blog-api
spec:
  selector:
    app: blog-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
