apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-service

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml

commonLabels:
  app.kubernetes.io/name: blog-service
  app.kubernetes.io/managed-by: kustomize
